rm -r /usr/share/themes/Artwiz-boxed ;
rm -r /usr/share/themes/Bear2 ;
rm -r /usr/share/themes/Clearlooks ;
rm -r /usr/share/themes/Clearlooks-3.4 ;
rm -r /usr/share/themes/Clearlooks-Olive ;
rm -r /usr/share/themes/Default ;
rm -r /usr/share/themes/Emacs ;
rm -r /usr/share/themes/HighContrast ;
rm -r /usr/share/themes/Industrial ;
rm -r /usr/share/themes/Mikachu ;
rm -r /usr/share/themes/Mist ;
rm -r /usr/share/themes/Natura ;
rm -r /usr/share/themes/Nightmare ;
rm -r /usr/share/themes/Nightmare-01 ;
rm -r /usr/share/themes/Nightmare-02 ;
rm -r /usr/share/themes/Nightmare-03 ;
rm -r /usr/share/themes/Onyx-Citrus ;
rm -r /usr/share/themes/Orang ;
rm -r /usr/share/themes/Raleigh ;
rm -r /usr/share/themes/Redmond ;
rm -r /usr/share/themes/Syscrash ;
rm -r /usr/share/themes/ThinIce ;

echo "rmthemes" ;